AllCops:
# 除外するディレクトリ（自動生成されたファイル）
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - config/**/*
    - config/*
    - Guardfile
    - Rakefile
    - Gemfile

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "AsciiComments: Use only ascii symbols in comments."を無効
Style/AsciiComments:
  Enabled: false

# "LineLength: Line is too long."を90まで引き上げ無効
LineLength:
  Max: 90

# /AbcSize: Assignment Branch Condition size for create is too high. を40まで引き上げ
Metrics/AbcSize:
  Max: 40

# "Metrics/MethodLength: Method has too many lines."の長さを20行にまで引き上げ
MethodLength:
  Max: 20

PredicateName:
  NamePrefixBlacklist:
    - has_
    - have_
